# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: 
  project_card:
    types: [moved]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Check move from "TODO" to "IN PROGRESS"
          id: check
          uses: vazexqi/salesforcedx-kanban-actions/project_card-check-movement@master
          with:
              token: ${{ secrets.GITHUB_TOKEN}}
              fromColumnId: ${{ github.event.changes.column_id.from }}
              fromColumnName: TODO
              toColumnId: ${{ github.event.project_card.column_id }}
              toColumnName: IN PROGRESS
